demo/demo/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url

from .views import CategoryEncodingView, ScalarEncodingView, DateEncodingView

urlpatterns = [
    url(r'^$', CategoryEncodingView.as_view(), name='categoryencoding'),

	url(r'^categoryencoding$', CategoryEncodingView.as_view(), name='categoryencoding'),
	url(r'^scalarencoding$', ScalarEncodingView.as_view(), name='scalarencoding'),
	url(r'^dateencoding$', DateEncodingView.as_view(), name='dateencoding'),
]

bootstrap3/models.py
# -*- coding: utf-8 -*-

# Empty models.py, required file for Django tests

bootstrap3/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.admin.widgets import AdminFileWidget
from django.forms import (
    HiddenInput, FileInput, CheckboxSelectMultiple, Textarea, TextInput,
    PasswordInput, NumberInput, EmailInput, URLInput,
)
from django.forms.widgets import CheckboxInput
from django.utils.safestring import mark_safe

from .bootstrap import (
    get_bootstrap_setting, get_form_renderer, get_field_renderer,
    get_formset_renderer,
    DBS3_SET_REQUIRED_SET_DISABLED)
from .components import render_icon
from .exceptions import BootstrapError
from .text import text_concat, text_value
from .utils import add_css_class, render_tag

FORM_GROUP_CLASS = 'form-group'

WIDGETS_NO_REQUIRED = (
    AdminFileWidget,
    HiddenInput,
    FileInput,
    CheckboxInput,
    CheckboxSelectMultiple
)


def render_formset(formset, **kwargs):
    """
    Render a formset to a Bootstrap layout
    """
    renderer_cls = get_formset_renderer(**kwargs)
    return renderer_cls(formset, **kwargs).render()


def render_formset_errors(formset, **kwargs):
    """
    Render formset errors to a Bootstrap layout
    """
    renderer_cls = get_formset_renderer(**kwargs)
    return renderer_cls(formset, **kwargs).render_errors()


def render_form(form, **kwargs):
    """
    Render a form to a Bootstrap layout
    """
    renderer_cls = get_form_renderer(**kwargs)
    return renderer_cls(form, **kwargs).render()


def render_form_errors(form, error_types='non_field_errors', **kwargs):
    """
    Render form errors to a Bootstrap layout
    """
    renderer_cls = get_form_renderer(**kwargs)
    return renderer_cls(form, **kwargs).render_errors(error_types)


def render_field(field, **kwargs):
    """
    Render a field to a Bootstrap layout
    """
    renderer_cls = get_field_renderer(**kwargs)
    return renderer_cls(field, **kwargs).render()


def render_label(content, label_for=None, label_class=None, label_title=''):
    """
    Render a label with content
    """
    attrs = {}
    if label_for:
        attrs['for'] = label_for
    if label_class:
        attrs['class'] = label_class
    if label_title:
        attrs['title'] = label_title
    return render_tag('label', attrs=attrs, content=content)


def render_button(
        content, button_type=None, icon=None, button_class='btn-default', size='',
        href='', name=None, value=None, title=None, extra_classes='', id=''):
    """
    Render a button with content
    """
    attrs = {}
    classes = add_css_class('btn', button_class)
    size = text_value(size).lower().strip()
    if size == 'xs':
        classes = add_css_class(classes, 'btn-xs')
    elif size == 'sm' or size == 'small':
        classes = add_css_class(classes, 'btn-sm')
    elif size == 'lg' or size == 'large':
        classes = add_css_class(classes, 'btn-lg')
    elif size == 'md' or size == 'medium':
        pass
    elif size:
        raise BootstrapError(
            'Parameter "size" should be "xs", "sm", "lg" or ' +
            'empty ("{}" given).'.format(size))
    if button_type:
        if button_type not in ('submit', 'reset', 'button', 'link'):
            raise BootstrapError(
                'Parameter "button_type" should be "submit", "reset", ' +
                '"button", "link" or empty  ("{}" given).'.format(button_type))
        attrs['type'] = button_type
    classes = add_css_class(classes, extra_classes)
    attrs['class'] = classes
    icon_content = render_icon(icon) if icon else ''
    if href:
        attrs['href'] = href
        tag = 'a'
    else:
        tag = 'button'
    if id:
        attrs['id'] = id
    if name:
        attrs['name'] = name
    if value:
        attrs['value'] = value
    if title:
        attrs['title'] = title
    return render_tag(
        tag,
        attrs=attrs,
        content=mark_safe(text_concat(icon_content, content, separator=' ')),
    )


def render_field_and_label(
        field, label, field_class='', label_for=None, label_class='',
        layout='', **kwargs):
    """
    Render a field with its label
    """
    if layout == 'horizontal':
        if not label_class:
            label_class = get_bootstrap_setting('horizontal_label_class')
        if not field_class:
            field_class = get_bootstrap_setting('horizontal_field_class')
        if not label:
            label = mark_safe('&#160;')
        label_class = add_css_class(label_class, 'control-label')
    html = field
    if field_class:
        html = '<div class="{klass}">{html}</div>'.format(
            klass=field_class, html=html)
    if label:
        html = render_label(
            label, label_for=label_for, label_class=label_class) + html
    return html


def render_form_group(content, css_class=FORM_GROUP_CLASS):
    """
    Render a Bootstrap form group
    """
    return '<div class="{klass}">{content}</div>'.format(
        klass=css_class,
        content=content,
    )


def is_widget_required_attribute(widget):
    """
    Is this widget required?
    """
    if DBS3_SET_REQUIRED_SET_DISABLED and not get_bootstrap_setting('set_required'):
        return False
    if not widget.is_required:
        return False
    if isinstance(widget, WIDGETS_NO_REQUIRED):
        return False
    return True


def is_widget_with_placeholder(widget):
    """
    Is this a widget that should have a placeholder?
    Only text, search, url, tel, e-mail, password, number have placeholders
    """
    return isinstance(widget, (TextInput, Textarea, NumberInput, EmailInput,
                               URLInput, PasswordInput))

demo/demo/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms
from django.forms.formsets import BaseFormSet, formset_factory

from bootstrap3.tests import TestForm

RADIO_CHOICES = (
    ('1', 'Radio 1'),
    ('2', 'Radio 2'),
)

MEDIA_CHOICES = (
    ('Audio', (
        ('vinyl', 'Vinyl'),
        ('cd', 'CD'),
    )),
    ('Video', (
        ('vhs', 'VHS Tape'),
        ('dvd', 'DVD'),
    )),
    ('unknown', 'Unknown'),
)


class ContactForm(TestForm):
    pass


class ContactBaseFormSet(BaseFormSet):
    def add_fields(self, form, index):
        super(ContactBaseFormSet, self).add_fields(form, index)

    def clean(self):
        super(ContactBaseFormSet, self).clean()
        raise forms.ValidationError("This error was added to show the non form errors styling")


ContactFormSet = formset_factory(TestForm, formset=ContactBaseFormSet,
                                 extra=2,
                                 max_num=4,
                                 validate_max=True)


class FilesForm(forms.Form):
    text1 = forms.CharField()
    file1 = forms.FileField()
    file2 = forms.FileField(required=False)
    file3 = forms.FileField(widget=forms.ClearableFileInput)
    file5 = forms.ImageField()
    file4 = forms.FileField(required=False, widget=forms.ClearableFileInput)


class ArticleForm(forms.Form):
    title = forms.CharField()
    pub_date = forms.DateField()

    def clean(self):
        cleaned_data = super(ArticleForm, self).clean()
        raise forms.ValidationError("This error was added to show the non field errors styling.")
        return cleaned_data

demo/demo/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.core.files.storage import default_storage

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models.fields.files import FieldFile
from django.views.generic import FormView
from django.views.generic.base import TemplateView
from django.contrib import messages

from .forms import ContactForm, FilesForm, ContactFormSet


class CategoryEncodingView(TemplateView):
    template_name = 'demo/categoryencoding.html'
	
class ScalarEncodingView(TemplateView):
    template_name = 'demo/scalarencoding.html'
	
class DateEncodingView(TemplateView):
    template_name = 'demo/dateencoding.html'

bootstrap3/templates/bootstrap3/bootstrap3.html
<!DOCTYPE html>
{% load bootstrap3 %}
<html{% if LANGUAGE_CODE %} lang="{{ LANGUAGE_CODE }}"{% endif %}>

<head>
    <meta charset="utf-8">
    <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge" /><![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block bootstrap3_title %}django-bootstrap3 template title{% endblock %}</title>
    {% bootstrap_css %}
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% if 'javascript_in_head'|bootstrap_setting %}{% bootstrap_javascript jquery=True %}{% endif %}
    {% block bootstrap3_extra_head %}{% endblock %}
</head>

<body>
{% block bootstrap3_content %}django-bootstrap3 template content{% endblock %}
{% if not 'javascript_in_head'|bootstrap_setting %}{% bootstrap_javascript jquery=True %}{% endif %}
{% block bootstrap3_extra_script %}{% endblock %}
</body>

</html>

bootstrap3/templates/bootstrap3/field_help_text_and_errors.html
{# Reverse the messages, so that errors are printed first #}
{% for text in help_text_and_errors reversed %}
    <div class="help-block">{{ text }}</div>
{% endfor %}

bootstrap3/templates/bootstrap3/form_errors.html
<div class="alert alert-danger alert-dismissable alert-link">
    <button class="close" type="button" data-dismiss="alert" aria-hidden="true">&#215;</button>
    {% for error in errors %}
        {{ error }}{% if not forloop.last %}<br>{% endif %}
    {% endfor %}
</div>

bootstrap3/templates/bootstrap3/messages.html
{% load bootstrap3 %}
{% for message in messages %}
    <div class="{{ message|bootstrap_message_classes }} alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&#215;</button>
        {{ message }}
    </div>
{% endfor %}

bootstrap3/templates/bootstrap3/pagination.html
{% load bootstrap3 %}
{% with bpurl=bootstrap_pagination_url|default:"" %}

    <ul class="{{ pagination_css_classes }}">

        {% if current_page == 1 %}
            <li class="prev disabled"><a>&laquo;</a></li>
        {% else %}
            <li class="prev">
                <a href="{% bootstrap_url_replace_param bpurl parameter_name 1 %}">&laquo;</a>
            </li>
        {% endif %}

        {% if pages_back %}
            <li>
                <a href="{% bootstrap_url_replace_param bpurl parameter_name pages_back %}">&hellip;</a>
            </li>
        {% endif %}

        {% for p in pages_shown %}
            {% if current_page == p %}
                <li class="active">
                    <a>{{ p }}</a>
                </li>
            {% else %}
                <li>
                    <a href="{% bootstrap_url_replace_param bpurl parameter_name p %}">{{ p }}</a>
                </li>
            {% endif %}
        {% endfor %}

        {% if pages_forward %}
            <li>
                <a href="{% bootstrap_url_replace_param bpurl parameter_name pages_forward %}">&hellip;</a>
            </li>
        {% endif %}

        {% if current_page == num_pages %}
            <li class="last disabled">
                <a>&raquo;</a>
            </li>
        {% else %}
            <li class="last">
                <a href="{% bootstrap_url_replace_param bpurl parameter_name num_pages %}">&raquo;</a>
            </li>
        {% endif %}

    </ul>

{% endwith %}

demo/demo/templates/demo/base.html
{% extends 'demo/bootstrap.html' %}

{% load bootstrap3 %}

{% block bootstrap3_content %}
    <div class="container">
        <h1>{% block title %}(no title){% endblock %}</h1>

        

        {% autoescape off %}{% bootstrap_messages %}{% endautoescape %}

        {% block content %}(no content){% endblock %}
    </div>

{% endblock %}

demo/demo/templates/demo/bootstrap.html
{% extends 'bootstrap3/bootstrap3.html' %}

{% block bootstrap3_title %}{% block title %}{% endblock %}{% endblock %}

demo/demo/templates/demo/categoryencoding.html
{% extends 'demo/base.html' %}

{% load bootstrap3 %}

{% block title %}
    HTM Framework
{% endblock %}

{% block content %}

	<ul class="nav nav-tabs">  
  <li role="presentation" class="active"><a href="http://localhost:8000/categoryencoding">Category Encoding</a></li>
  <li role="presentation"><a href="http://localhost:8000/scalarencoding">Scalar Encoding</a></li>
  <li role="presentation"><a href="http://localhost:8000/dateencoding">Date Encoding</a></li>
	</ul>

	<p></p>
	<div class="form-group bootstrap3-required"><label class="control-label" for="id_file1">Upload Data</label><div class="row bootstrap3-multi-input"><div class="col-xs-12"><input type="file" name="file1" title="" required class="" id="id_file1" /></div></div></div>
    
	<div class="form-group"><label class="control-label" for="id_message">N</label><div class="control-label"><input type="text" name="N" title="my_help_text" placeholder="0" class="form-control" id="id_N" /></div></div>
	<div class="form-group"><label class="control-label" for="id_message">W</label><div class="control-label"><input type="text" name="W" title="my_help_text" placeholder="0" class="form-control" id="id_W" /></div></div>
	<div class="form-group"><label class="control-label" for="id_message">CategoryList</label><div class="control-label"><input type="text" name="CategoryList" title="my_help_text" placeholder="0" class="form-control" id="id_CategoryList" /></div></div>
	<div class="form-group"><label class="control-label" for="id_message">Name</label><div class="control-label"><input type="text" name="Name" title="my_help_text" placeholder="" class="form-control" id="id_Name" /></div></div>
	<div class="form-group"><label class="control-label" for="id_message">Verbosity</label><div class="control-label"><input type="text" name="Verbosity" title="my_help_text" placeholder="0" class="form-control" id="id_Verbosity" /></div></div>
	<div class="form-group"><label class="control-label" for="id_message">Seed</label><div class="control-label"><input type="text" name="Seed" title="my_help_text" placeholder="1" class="form-control" id="id_Seed" /></div></div>
	<div class="form-group"><label class="control-label" for="id_message">Forced</label><div class="control-label"><input type="text" name="Forced" title="my_help_text" placeholder="False" class="form-control" id="id_Forced" /></div></div>

	
	<div class="form-group bootstrap3-req"><label class="control-label">Other Options</label><div class="control-label"><div id="id_category2">    
	<div class="checkbox"><label for="id_category2_0"><input type="checkbox" name="category2" value="1" id="id_category2_0" class=""  />
	Spatial Pooling</label></div>
    
	<div class="checkbox"><label for="id_category2_1"><input type="checkbox" name="category2" value="2" id="id_category2_1" class=""  />
	Temporal Memory</label></div>
	
	<div class="checkbox"><label for="id_category2_2"><input type="checkbox" name="category2" value="3" id="id_category2_2" class=""  />
	Classify Data</label></div>
	
	<div class="checkbox"><label for="id_category2_3"><input type="checkbox" name="category2" value="4" id="id_category2_3" class=""  />
	Detect Anomaly</label></div>	
	</div>
	
	{% bootstrap_button "Run" button_type="submit" button_class="btn-primary" %}

</div></div>
	
{% endblock %}

demo/demo/templates/demo/encodingresults.html
<html>
<head>  
 
  
  
  
  
 
  </head>  
  <body> 
   </body>
</html>

demo/demo/templates/demo/form_by_field.html
{% extends 'demo/base.html' %}

{% load bootstrap3 %}

{% block title %}
    Forms
{% endblock %}

{% block content %}

    <form role="form" method="post">
        {% csrf_token %}
        {% bootstrap_form_errors form type='non_fields' %}
        {% bootstrap_field form.subject layout='horizontal' size='sm' %}
        {% bootstrap_field form.message placeholder='bonkers' %}
        {% buttons submit='OK' reset="Cancel" %}{% endbuttons %}
    </form>

{% endblock %}

demo/demo/templates/demo/form_horizontal.html
{% extends 'demo/base.html' %}

{% load bootstrap3 %}

{% block title %}
    Forms
{% endblock %}

{% block content %}

    <form role="form" class="form-horizontal" method="post">
        {% csrf_token %}
        {% bootstrap_form form layout="horizontal" %}
        {% buttons submit='OK' reset='Cancel' layout='horizontal' %}{% endbuttons %}
    </form>

{% endblock %}

demo/demo/templates/demo/form_with_files.html
{% extends 'demo/base.html' %}

{% load bootstrap3 %}

{% block title %}
    Forms
{% endblock %}

{% block content %}

    <form role="form" method="post" enctype="multipart/form-data" {% if layout != 'vertical' %}class="form-{{ layout }}"{% endif %}>
        {% csrf_token %}
        {% bootstrap_form form layout=layout %}
        {% buttons submit='OK' reset="Cancel" %}{% endbuttons %}
    </form>

{% endblock %}